# Generated by Django 2.2 on 2019-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
