# Generated by Django 2.2 on 2019-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190501_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
