# Generated by Django 2.2 on 2019-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190501_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contnet',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
