# Generated by Django 2.2 on 2019-05-01 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('url', models.TextField()),
                ('identifier', models.TextField()),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='profiles.Profile')),
            ],
            options={
                'db_table': 'pl_pages',
            },
        ),
    ]
