# Generated by Django 2.2 on 2019-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190501_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(),
        ),
    ]
